import { nanoid } from "nanoid";
import {
  boolean,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
  jsonb,
  real,
  index,
  uniqueIndex,
  AnyPgColumn,
} from "drizzle-orm/pg-core";

// ============================================================
// ENUMS
// ============================================================

/**
 * Application-level roles. Clerk handles authentication;
 * this enum drives authorization and UI routing only.
 */
export const userRole = pgEnum("user_role", ["STUDENT", "PARENT", "ADMIN"]);

/**
 * Lifecycle of an AI tutoring session.
 * PAUSED = student closed mid-session (resume via currentChunkId).
 */
export const learningSessionStatus = pgEnum("learning_session_status", [
  "UPCOMING",
  "ACTIVE",
  "PAUSED",
  "COMPLETED",
  "CANCELLED",
]);

/** Type classification for a mock test as a whole. */
export const testType = pgEnum("test_type", [
  "MCQ",
  "SHORT_ANSWER",
  "LONG_ANSWER",
  "MIXED",
]);

/** Per-question type within a test or question bank. */
export const questionType = pgEnum("question_type", [
  "MCQ",
  "SHORT_ANSWER",
  "LONG_ANSWER",
  "TRUE_FALSE",
  "FILL_IN_BLANK",
]);

/** Difficulty classification used across questions and PYQs. */
export const difficultyLevel = pgEnum("difficulty_level", [
  "EASY",
  "MEDIUM",
  "HARD",
]);

/**
 * Inngest async job status — shared across books, chapters, and PYQ papers.
 * PARTIAL = some pages processed but job failed mid-way (can be resumed).
 */
export const processingStatus = pgEnum("processing_status", [
  "PENDING",
  "PROCESSING",
  "COMPLETED",
  "FAILED",
  "PARTIAL",
]);

/**
 * Which external storage provider holds a file.
 * Original PDFs  → Supabase Storage.
 * Page images    → Vercel Blob.
 */
export const storageProvider = pgEnum("storage_provider", [
  "VERCEL_BLOB",
  "SUPABASE_STORAGE",
  "S3",
]);

/**
 * Role of a platform AI agent.
 * TUTOR     = reads pdfChunks sequentially, speaks speakText, highlights PDF.
 * ASSESSOR  = runs mock tests, evaluates student answers.
 */
export const agentRole = pgEnum("agent_role", ["TUTOR", "ASSESSOR"]);

/**
 * Source of an importantQuestions row.
 * BOOK         = NCERT textbook exercises / intext questions.
 * PYQ          = extracted from a previous year question paper.
 * AI_GENERATED = generated by OpenAI post chapter-processing.
 */
export const questionSource = pgEnum("question_source", [
  "BOOK",
  "PYQ",
  "AI_GENERATED",
]);

/** Student's preferred spoken language during AI sessions. */
export const languagePreference = pgEnum("language_preference", [
  "ENGLISH",
  "HINGLISH",
]);

// ============================================================
// USER PROFILES  (Clerk manages auth; we store app data only)
// ============================================================

/**
 * userProfiles: App-level profile for every Clerk user.
 *
 * Clerk is the source of truth for email, password, and OAuth sessions.
 * We sync name + email here via a Clerk webhook (CLERK_WEBHOOK_SECRET).
 *
 * clerkId  — Clerk's own user ID, e.g. "user_2abc…". Required for all
 *             webhook lookups and tRPC context user identification.
 * parentId — FK to another PARENT-role userProfiles row. Used for the
 *             parent monitoring dashboard.
 */
export const userProfiles = pgTable(
  "user_profiles",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    clerkId: text("clerk_id").notNull().unique(),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),
    image: text("image"),
    role: userRole("role").notNull().default("STUDENT"),
    /** CBSE class number: 9, 10, 11, or 12. Only set for STUDENT role. */
    class: integer("class"),
    school: text("school"),
    phone: text("phone"),
    city: text("city"),
    languagePreference: languagePreference("language_preference")
      .notNull()
      .default("ENGLISH"),
    /** FK to a PARENT-role userProfiles row. Null until parent links child. */
    parentId: text("parent_id").references((): AnyPgColumn => userProfiles.id, {
      onDelete: "set null",
    }),
    isOnboarded: boolean("is_onboarded").notNull().default(false),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_user_profiles_clerk_id").on(t.clerkId),
    index("idx_user_profiles_parent_id").on(t.parentId),
    index("idx_user_profiles_role_class").on(t.role, t.class),
  ],
);

// ============================================================
// CONTENT TAXONOMY
// ============================================================

/**
 * subjects: Master list of CBSE subjects (seeded by admin).
 * Examples: Mathematics, Physics, Chemistry, Biology, English, Hindi,
 *           History, Geography, Economics, Political Science.
 */
export const subjects = pgTable("subjects", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => nanoid()),
  name: text("name").notNull(),
  /** Short machine-readable code: MATH, PHY, CHEM, BIO, ENG, HIN, etc. */
  code: text("code").notNull().unique(),
  description: text("description"),
  /** Lucide icon name for UI display, e.g. "flask-conical". */
  icon: text("icon"),
  /** Tailwind-compatible hex color for subject chips, e.g. "#6366f1". */
  color: text("color"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/**
 * classes: CBSE class numbers 9–12 (seeded, not user-created).
 * Kept as a table so we can attach metadata and join cleanly in analytics.
 */
export const classes = pgTable("classes", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => nanoid()),
  name: text("name").notNull(),
  /** Integer 9, 10, 11, or 12. Unique constraint prevents duplicates. */
  number: integer("number").notNull().unique(),
  description: text("description"),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/**
 * classSubjects: Junction table — which subjects are offered in which class.
 * E.g. Biology exists in Class 11 & 12 but not 9 & 10 (Science stream).
 * Seeded by admin during platform setup.
 */
export const classSubjects = pgTable(
  "class_subjects",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    classId: text("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    subjectId: text("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_class_subjects_class_subject").on(t.classId, t.subjectId),
    index("idx_class_subjects_class_id").on(t.classId),
    index("idx_class_subjects_subject_id").on(t.subjectId),
  ],
);

// ============================================================
// BOOK CONTENT PIPELINE
// ============================================================

/**
 * books: An NCERT or reference textbook uploaded by admin.
 *
 * Storage split:
 *   Original PDF  → Supabase Storage  (supabaseStorageUrl)
 *   Page images   → Vercel Blob       (bookPages.imageUrl)
 *
 * processingStatus tracks the Inngest pipeline:
 *   PENDING → PROCESSING → COMPLETED (or FAILED / PARTIAL)
 */
export const books = pgTable(
  "books",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    subjectId: text("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    classId: text("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description"),
    author: text("author"),
    publisher: text("publisher"),
    isbn: text("isbn"),
    /** Supabase Storage path/URL for the original uploaded PDF. */
    supabaseStorageUrl: text("supabase_storage_url"),
    /** Vercel Blob URL if the PDF is mirrored there (optional / future). */
    vercelBlobUrl: text("vercel_blob_url"),
    storageProvider: storageProvider("storage_provider")
      .notNull()
      .default("SUPABASE_STORAGE"),
    /** File size in bytes. */
    pdfSize: integer("pdf_size"),
    /**
     * When the book was created from one PDF per chapter, stores each chapter’s
     * Supabase path/URL in order so reprocessing can re-run the same pipeline.
     */
    chapterIngestSources: jsonb("chapter_ingest_sources").$type<
      | {
          chapterNumber: number;
          supabaseStorageUrl: string;
          title?: string;
        }[]
      | null
    >(),
    /** Set for per-chapter uploads — should match `chapter_ingest_sources` length. */
    expectedChapterCount: integer("expected_chapter_count"),
    totalPages: integer("total_pages").notNull().default(0),
    coverImage: text("cover_image"),
    processingStatus: processingStatus("processing_status")
      .notNull()
      .default("PENDING"),
    isActive: boolean("is_active").notNull().default(true),
    uploadedAt: timestamp("uploaded_at").notNull().defaultNow(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_books_subject_class").on(t.subjectId, t.classId),
    index("idx_books_processing_status").on(t.processingStatus),
  ],
);

/**
 * bookPages: One row per PDF page.
 *
 * imageUrl: Vercel Blob URL for the rendered page image (PNG/WebP),
 *           used by the left-panel PDF viewer in the learning session.
 * textContent: raw text from pdfjs-dist (may be garbled for equations).
 * hasEquations / hasImages: set during processing so the pipeline and
 *   frontend can apply GPT-4o Vision fallback where needed.
 */
export const bookPages = pgTable(
  "book_pages",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    bookId: text("book_id")
      .notNull()
      .references(() => books.id, { onDelete: "cascade" }),
    /** 1-based page number matching the PDF page index. */
    pageNumber: integer("page_number").notNull(),
    /** Vercel Blob URL for the rendered page image shown in the viewer. */
    imageUrl: text("image_url").notNull(),
    /** Raw text extracted by pdfjs-dist for this page. */
    textContent: text("text_content"),
    chapterTitle: text("chapter_title"),
    chapterNumber: integer("chapter_number"),
    isChapterStart: boolean("is_chapter_start").notNull().default(false),
    /** True if pdfjs-dist detected math/equation operators on this page. */
    hasEquations: boolean("has_equations").notNull().default(false),
    /** True if pdfjs-dist detected embedded images/diagrams on this page. */
    hasImages: boolean("has_images").notNull().default(false),
    /** Extra pdfjs page metadata (viewport dimensions, rotation, etc.). */
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_book_pages_book_page").on(t.bookId, t.pageNumber),
    index("idx_book_pages_book_id").on(t.bookId),
    index("idx_book_pages_chapter_number").on(t.bookId, t.chapterNumber),
  ],
);

/**
 * chapters: Logical chapter within a book spanning startPage → endPage.
 *
 * processingStatus: tracks whether pdfChunks have been extracted.
 * totalChunks: denormalized count updated at the end of the Inngest job.
 * questionsGenerated: set true once importantQuestions have been AI-generated.
 */
export const chapters = pgTable(
  "chapters",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    bookId: text("book_id")
      .notNull()
      .references(() => books.id, { onDelete: "cascade" }),
    subjectId: text("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    classId: text("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    chapterNumber: integer("chapter_number").notNull(),
    startPage: integer("start_page").notNull(),
    endPage: integer("end_page").notNull(),
    description: text("description"),
    /** Learning objectives in markdown format. */
    objectives: text("objectives"),
    /** Estimated AI tutoring session duration in minutes. */
    duration: integer("duration"),
    processingStatus: processingStatus("processing_status")
      .notNull()
      .default("PENDING"),
    /**
     * Denormalized total pdfChunks for this chapter.
     * Used for fast completion percentage:
     *   completionPct = (currentChunkIndex / totalChunks) * 100
     */
    totalChunks: integer("total_chunks").notNull().default(0),
    /** True once importantQuestions have been generated for this chapter. */
    questionsGenerated: boolean("questions_generated").notNull().default(false),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_chapters_book_chapter_num").on(t.bookId, t.chapterNumber),
    index("idx_chapters_book_id").on(t.bookId),
    index("idx_chapters_subject_class").on(t.subjectId, t.classId),
    index("idx_chapters_processing_status").on(t.processingStatus),
  ],
);

// ============================================================
// PDF CHUNKS  (the core of the AI tutoring session)
// ============================================================

/**
 * pdfChunks: Paragraph/section-level text chunks extracted from each page.
 *
 * This is THE most critical table for the padh.ai tutoring feature.
 *
 * How the pipeline produces this:
 *   1. Inngest job fetches the original PDF from Supabase Storage.
 *   2. pdfjs-dist extracts text items with bounding-box coordinates
 *      (x, y, width, height in PDF user units = points, 1pt = 1/72 inch).
 *   3. Nearby text items are grouped into paragraph-level chunks.
 *   4. For chunks where pdfjs-dist returns garbled text (equations, images),
 *      GPT-4o Vision is called with the page image to generate a description.
 *   5. speakText is set to the final text the AI agent should speak.
 *   6. orderInChapter is a global sequential integer across all pages
 *      of the chapter, driving the AI session playback order.
 *
 * How the frontend uses this at runtime:
 *   1. AI agent speaks speakText for the current chunk.
 *   2. Frontend receives the chunkId via an OpenAI Realtime custom event.
 *   3. Frontend fetches boundingBoxes for that chunk.
 *   4. Frontend converts PDF-unit coordinates to pixel offsets:
 *        pixelX = (box.x / box.pageWidth)  * renderedImageWidthPx
 *        pixelY = (box.y / box.pageHeight) * renderedImageHeightPx
 *   5. A highlight <div> overlay is positioned on top of the page image,
 *      creating the live paragraph-highlight effect.
 *
 * boundingBoxes JSONB schema (array of objects):
 *   [{ x: number, y: number, width: number, height: number,
 *      pageWidth: number, pageHeight: number }]
 */
export const pdfChunks = pgTable(
  "pdf_chunks",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    bookPageId: text("book_page_id")
      .notNull()
      .references(() => bookPages.id, { onDelete: "cascade" }),
    chapterId: text("chapter_id")
      .notNull()
      .references(() => chapters.id, { onDelete: "cascade" }),
    /** Zero-based index of this chunk within its page. */
    chunkIndex: integer("chunk_index").notNull(),
    /**
     * Global ordering across ALL pages of the chapter (0-based).
     * Drives sequential AI playback: ORDER BY orderInChapter ASC.
     * Also used for resume: WHERE orderInChapter >= currentChunkIndex.
     */
    orderInChapter: integer("order_in_chapter").notNull(),
    /** Raw text as extracted by pdfjs-dist. May be garbled for equations. */
    text: text("text").notNull(),
    /**
     * Bounding box coordinates for every text run in this chunk.
     * Schema: { x, y, width, height, pageWidth, pageHeight }[]
     * All values are in PDF user units (points).
     * Frontend scales to pixel offsets using the rendered image dimensions.
     */
    boundingBoxes: jsonb("bounding_boxes").notNull(),
    /**
     * True when pdfjs-dist cannot reliably extract the text (math equations).
     * When true, equationDescription is used for TTS instead of text.
     */
    isEquation: boolean("is_equation").notNull().default(false),
    /** GPT-4o Vision spoken description of the equation. Null if not an equation. */
    equationDescription: text("equation_description"),
    /** True when this chunk is primarily an embedded image or diagram. */
    isImage: boolean("is_image").notNull().default(false),
    /** GPT-4o Vision spoken description of the image. Null if not an image. */
    imageDescription: text("image_description"),
    /**
     * The exact text the AI agent passes to OpenAI Realtime API TTS.
     * - Normal text  → cleaned version of the text field.
     * - Equation     → equationDescription in natural spoken form.
     * - Image        → imageDescription narrated naturally.
     * Always safe to pass directly; never contains raw LaTeX or garbled chars.
     */
    speakText: text("speak_text").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    /** THE hottest query: fetch all chunks for a chapter in playback order. */
    index("idx_pdf_chunks_chapter_order").on(t.chapterId, t.orderInChapter),
    /** Prevent duplicate extraction on re-processing runs. */
    uniqueIndex("uq_pdf_chunks_page_chunk_idx").on(t.bookPageId, t.chunkIndex),
    index("idx_pdf_chunks_book_page_id").on(t.bookPageId),
    /** Let the pipeline handle equation chunks separately. */
    index("idx_pdf_chunks_chapter_equation").on(t.chapterId, t.isEquation),
  ],
);

// ============================================================
// INNGEST PIPELINE TRACKING
// ============================================================

/**
 * bookProcessingJobs: One row per Inngest PDF processing run per book.
 *
 * A book may be re-processed after a failed run, creating a new row each time.
 * The most recent COMPLETED row for a bookId is the canonical state.
 *
 * inngestRunId: the Inngest function run ID for debugging in Inngest dashboard.
 * pagesProcessed / chunksExtracted: live counters updated by each Inngest step.
 */
export const bookProcessingJobs = pgTable(
  "book_processing_jobs",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    bookId: text("book_id")
      .notNull()
      .references(() => books.id, { onDelete: "cascade" }),
    /** The Inngest function run ID returned from inngest.send(). */
    inngestRunId: text("inngest_run_id"),
    status: processingStatus("status").notNull().default("PENDING"),
    pagesProcessed: integer("pages_processed").notNull().default(0),
    chunksExtracted: integer("chunks_extracted").notNull().default(0),
    /** Human-readable error detail when status = FAILED. */
    errorMessage: text("error_message"),
    /** Arbitrary step-level metadata from the Inngest job (e.g. retry count). */
    metadata: jsonb("metadata"),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_book_processing_jobs_book_id").on(t.bookId),
    index("idx_book_processing_jobs_status").on(t.status),
    index("idx_book_processing_jobs_inngest_run").on(t.inngestRunId),
  ],
);

// ============================================================
// PREVIOUS YEAR QUESTION PAPERS
// ============================================================

/**
 * pyqPapers: A complete PYQ paper uploaded by admin.
 * Individual questions extracted from this paper go into importantQuestions.
 */
export const pyqPapers = pgTable(
  "pyq_papers",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    classId: text("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    subjectId: text("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    /** Year of the exam, e.g. 2023. */
    examYear: integer("exam_year").notNull(),
    /** Board name: CBSE, ICSE, State Board, etc. */
    boardName: text("board_name").notNull().default("CBSE"),
    /** Supabase Storage URL of the original PDF. */
    pdfUrl: text("pdf_url").notNull(),
    coverImage: text("cover_image"),
    totalMarks: integer("total_marks"),
    durationMinutes: integer("duration_minutes"),
    processingStatus: processingStatus("processing_status")
      .notNull()
      .default("PENDING"),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_pyq_papers_class_subject").on(t.classId, t.subjectId),
    index("idx_pyq_papers_exam_year").on(t.examYear),
  ],
);

// ============================================================
// IMPORTANT QUESTIONS  (standalone question bank per chapter)
// ============================================================

/**
 * importantQuestions: Admin-curated or AI-generated important questions.
 *
 * Separate from mock test questions. Shown in the "Important Questions" tab
 * after a student completes a chapter.
 *
 * Sources:
 *   BOOK         → NCERT intext/exercise questions extracted by AI.
 *   PYQ          → Questions extracted from a pyqPapers PDF.
 *   AI_GENERATED → Generated by GPT-4o using chapter content.
 */
export const importantQuestions = pgTable(
  "important_questions",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    chapterId: text("chapter_id")
      .notNull()
      .references(() => chapters.id, { onDelete: "cascade" }),
    /** Non-null when source = PYQ. */
    pyqPaperId: text("pyq_paper_id").references(() => pyqPapers.id, {
      onDelete: "set null",
    }),
    /** Non-null when question maps to a specific chunk of the book. */
    pdfChunkId: text("pdf_chunk_id").references(() => pdfChunks.id, {
      onDelete: "set null",
    }),
    questionText: text("question_text").notNull(),
    questionType: questionType("question_type").notNull(),
    /** For MCQ: { options: string[], correctIndex: number } */
    options: jsonb("options"),
    correctAnswer: text("correct_answer").notNull(),
    explanation: text("explanation"),
    marks: integer("marks").notNull().default(1),
    difficulty: difficultyLevel("difficulty").notNull().default("MEDIUM"),
    source: questionSource("source").notNull(),
    /** PYQ exam year, e.g. 2022. Null for non-PYQ sources. */
    pyqYear: integer("pyq_year"),
    /** Display order within the chapter's important questions list. */
    orderInChapter: integer("order_in_chapter").notNull().default(0),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_important_questions_chapter_order").on(
      t.chapterId,
      t.orderInChapter,
    ),
    index("idx_important_questions_pyq_paper").on(t.pyqPaperId),
    index("idx_important_questions_difficulty").on(t.chapterId, t.difficulty),
    index("idx_important_questions_source").on(t.chapterId, t.source),
  ],
);

// ============================================================
// AI TUTOR AGENTS
// ============================================================

/**
 * agents: Platform-level AI agents seeded by admins.
 * NOT user-created — one TUTOR and one ASSESSOR per subject+class combination.
 *
 * TUTOR agents:    read pdfChunks sequentially via OpenAI Realtime API WebRTC,
 *                  speak speakText, signal the frontend to highlight chunks.
 * ASSESSOR agents: run mock tests and evaluate student answers.
 *
 * voiceId: one of OpenAI's built-in voices:
 *   "alloy" | "echo" | "fable" | "onyx" | "nova" | "shimmer"
 */
export const agents = pgTable(
  "agents",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    name: text("name").notNull(),
    agentRole: agentRole("agent_role").notNull().default("TUTOR"),
    /** System prompt passed to OpenAI Realtime API for this agent. */
    instructions: text("instructions").notNull(),
    subjectId: text("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    classId: text("class_id")
      .notNull()
      .references(() => classes.id, { onDelete: "cascade" }),
    /** OpenAI Realtime voice ID. Default "nova" sounds friendly for students. */
    voiceId: text("voice_id").notNull().default("nova"),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_agents_subject_class_role").on(
      t.subjectId,
      t.classId,
      t.agentRole,
    ),
    index("idx_agents_subject_class").on(t.subjectId, t.classId),
  ],
);

// ============================================================
// LEARNING SESSIONS  (with chunk-level resume support)
// ============================================================

/**
 * learningSessions: One row per AI tutoring session a student starts.
 *
 * Session resume flow:
 *   1. Student opens a chapter.
 *   2. Query: WHERE studentId = ? AND chapterId = ? AND status IN ('ACTIVE','PAUSED').
 *   3. If found → read currentChunkIndex.
 *   4. Query pdfChunks WHERE chapterId = ? AND orderInChapter >= currentChunkIndex.
 *   5. Resume AI agent from that exact chunk — student continues seamlessly.
 *
 * currentChunkId:    FK to the exact pdfChunks row where session was paused.
 * currentChunkIndex: integer copy of orderInChapter (avoids a join on resume).
 * durationSeconds:   more granular than the old durationMinutes field.
 * chunksVisited:     ordered array of chunk IDs visited (for analytics).
 */
export const learningSessions = pgTable(
  "learning_sessions",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    studentId: text("student_id")
      .notNull()
      .references(() => userProfiles.id, { onDelete: "cascade" }),
    chapterId: text("chapter_id")
      .notNull()
      .references(() => chapters.id, { onDelete: "cascade" }),
    bookId: text("book_id")
      .notNull()
      .references(() => books.id, { onDelete: "cascade" }),
    agentId: text("agent_id").references(() => agents.id, {
      onDelete: "set null",
    }),
    title: text("title").notNull(),
    /** "full_explanation" | "quick_summary" | "weak_topics" */
    sessionType: text("session_type").notNull().default("full_explanation"),
    status: learningSessionStatus("status").notNull().default("UPCOMING"),
    /**
     * FK to the exact pdfChunks row where the student paused.
     * Null until the session transitions to ACTIVE.
     * Set to null again when status = COMPLETED.
     */
    currentChunkId: text("current_chunk_id").references(() => pdfChunks.id, {
      onDelete: "set null",
    }),
    /**
     * Integer copy of pdfChunks.orderInChapter for currentChunkId.
     * Stored denormalized so the resume query needs no join on pdfChunks.
     */
    currentChunkIndex: integer("current_chunk_index"),
    languagePreference: languagePreference("language_preference")
      .notNull()
      .default("ENGLISH"),
    startedAt: timestamp("started_at"),
    endedAt: timestamp("ended_at"),
    /** Actual session duration in seconds. */
    durationSeconds: integer("duration_seconds"),
    /** Full session transcript accumulated from OpenAI Realtime delta events. */
    transcript: text("transcript"),
    /** AI-generated study summary shown to student after session ends. */
    summary: text("summary"),
    /** AI-generated bullet-point notes for the student to review later. */
    aiNotes: text("ai_notes"),
    studentFeedback: text("student_feedback"),
    parentNotes: text("parent_notes"),
    /** Ordered array of pdfChunks IDs visited this session. */
    chunksVisited: jsonb("chunks_visited"),
    /** Ordered array of bookPages IDs viewed this session. */
    pagesVisited: jsonb("pages_visited"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    /** THE resume query: student + chapter + active/paused status. */
    index("idx_learning_sessions_student_chapter").on(t.studentId, t.chapterId),
    index("idx_learning_sessions_student_status").on(t.studentId, t.status),
    index("idx_learning_sessions_chapter_status").on(t.chapterId, t.status),
    /** Parent dashboard: fetch all recent sessions for a child. */
    index("idx_learning_sessions_student_created").on(t.studentId, t.createdAt),
  ],
);

// ============================================================
// MOCK TESTS & QUESTIONS
// ============================================================

/**
 * tests: AI-generated or admin-created mock tests per chapter.
 * Unlocked after a student completes a learning session for that chapter.
 */
export const tests = pgTable(
  "tests",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    chapterId: text("chapter_id")
      .notNull()
      .references(() => chapters.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description"),
    testType: testType("test_type").notNull(),
    /** Duration in minutes. */
    duration: integer("duration").notNull(),
    totalMarks: integer("total_marks").notNull(),
    passingMarks: integer("passing_marks").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [index("idx_tests_chapter_id").on(t.chapterId)],
);

/** questions: Individual questions belonging to a mock test. */
export const questions = pgTable(
  "questions",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    testId: text("test_id")
      .notNull()
      .references(() => tests.id, { onDelete: "cascade" }),
    chapterId: text("chapter_id")
      .notNull()
      .references(() => chapters.id, { onDelete: "cascade" }),
    /** Non-null when this question was generated from a specific chunk. */
    pdfChunkId: text("pdf_chunk_id").references(() => pdfChunks.id, {
      onDelete: "set null",
    }),
    questionText: text("question_text").notNull(),
    questionType: questionType("question_type").notNull(),
    /** For MCQ: { options: string[], correctIndex: number } */
    options: jsonb("options"),
    correctAnswer: text("correct_answer").notNull(),
    explanation: text("explanation"),
    marks: integer("marks").notNull().default(1),
    difficulty: difficultyLevel("difficulty").notNull().default("MEDIUM"),
    /** Display order within the test. */
    order: integer("order").notNull(),
    isActive: boolean("is_active").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_questions_test_id").on(t.testId),
    index("idx_questions_chapter_id").on(t.chapterId),
  ],
);

/**
 * testAttempts: One row each time a student attempts a mock test.
 * answers JSONB schema: { questionId: string; answer: string }[]
 */
export const testAttempts = pgTable(
  "test_attempts",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    testId: text("test_id")
      .notNull()
      .references(() => tests.id, { onDelete: "cascade" }),
    studentId: text("student_id")
      .notNull()
      .references(() => userProfiles.id, { onDelete: "cascade" }),
    startedAt: timestamp("started_at").notNull(),
    submittedAt: timestamp("submitted_at"),
    answers: jsonb("answers").notNull(),
    score: integer("score"),
    totalMarks: integer("total_marks").notNull(),
    /** Float percentage, e.g. 66.67. */
    percentage: real("percentage"),
    isPassed: boolean("is_passed"),
    /** Time spent in seconds. */
    timeSpentSeconds: integer("time_spent_seconds"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_test_attempts_student_test").on(t.studentId, t.testId),
    index("idx_test_attempts_student").on(t.studentId),
    index("idx_test_attempts_test_id").on(t.testId),
  ],
);

// ============================================================
// PROGRESS & ANALYTICS
// ============================================================

/**
 * studentProgress: Denormalized progress summary per student per chapter.
 *
 * Updated at session pause/end and after each test attempt.
 * Used by the student dashboard and parent monitoring panel.
 *
 * completionPercentage: 0.0–100.0 float, calculated as:
 *   (currentChunkIndex / chapter.totalChunks) * 100
 *
 * Composite unique on (studentId, chapterId) makes this upsert-friendly:
 *   INSERT ... ON CONFLICT (student_id, chapter_id) DO UPDATE SET ...
 */
export const studentProgress = pgTable(
  "student_progress",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    studentId: text("student_id")
      .notNull()
      .references(() => userProfiles.id, { onDelete: "cascade" }),
    chapterId: text("chapter_id")
      .notNull()
      .references(() => chapters.id, { onDelete: "cascade" }),
    /** 0.0 – 100.0 float. */
    completionPercentage: real("completion_percentage").notNull().default(0),
    lastAccessedAt: timestamp("last_accessed_at"),
    totalTimeSpentSeconds: integer("total_time_spent_seconds")
      .notNull()
      .default(0),
    sessionsCompleted: integer("sessions_completed").notNull().default(0),
    testsAttempted: integer("tests_attempted").notNull().default(0),
    /** Average mock test score as a float percentage. */
    averageScore: real("average_score"),
    /** Array of strong topic strings from the chapter. */
    strengths: jsonb("strengths"),
    /** Array of weak topic strings the student should revisit. */
    weaknesses: jsonb("weaknesses"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("uq_student_progress_student_chapter").on(
      t.studentId,
      t.chapterId,
    ),
    index("idx_student_progress_student").on(t.studentId),
    index("idx_student_progress_student_accessed").on(
      t.studentId,
      t.lastAccessedAt,
    ),
  ],
);

/**
 * learningAnalytics: Append-only event log for granular analytics.
 * Each row = one measurable event (session_time, test_score, chunk_completed…).
 * Used for admin dashboards and future ML-based recommendations.
 */
export const learningAnalytics = pgTable(
  "learning_analytics",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    studentId: text("student_id")
      .notNull()
      .references(() => userProfiles.id, { onDelete: "cascade" }),
    chapterId: text("chapter_id").references(() => chapters.id, {
      onDelete: "cascade",
    }),
    subjectId: text("subject_id").references(() => subjects.id, {
      onDelete: "cascade",
    }),
    sessionId: text("session_id").references(() => learningSessions.id, {
      onDelete: "set null",
    }),
    /**
     * Event type key. Examples:
     *   "session_started" | "session_paused" | "session_completed"
     *   "chunk_completed" | "test_score" | "question_asked"
     */
    metricType: text("metric_type").notNull(),
    metricValue: real("metric_value").notNull(),
    metadata: jsonb("metadata"),
    recordedAt: timestamp("recorded_at").notNull().defaultNow(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_learning_analytics_student").on(t.studentId),
    index("idx_learning_analytics_student_subject").on(
      t.studentId,
      t.subjectId,
    ),
    index("idx_learning_analytics_student_chapter").on(
      t.studentId,
      t.chapterId,
    ),
    index("idx_learning_analytics_recorded_at").on(t.recordedAt),
  ],
);

/**
 * pageInteractions: Fine-grained log of student↔AI interactions per session.
 * Used for session replay, agent training data, and parent reports.
 */
export const pageInteractions = pgTable(
  "page_interactions",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => nanoid()),
    sessionId: text("session_id")
      .notNull()
      .references(() => learningSessions.id, { onDelete: "cascade" }),
    bookPageId: text("book_page_id")
      .notNull()
      .references(() => bookPages.id, { onDelete: "cascade" }),
    /** The specific chunk active when this interaction occurred. */
    pdfChunkId: text("pdf_chunk_id").references(() => pdfChunks.id, {
      onDelete: "set null",
    }),
    studentId: text("student_id")
      .notNull()
      .references(() => userProfiles.id, { onDelete: "cascade" }),
    /**
     * Interaction type key. Examples:
     *   "question_asked" | "clarification_request"
     *   "chunk_completed" | "page_feedback" | "cross_question_answered"
     */
    interactionType: text("interaction_type").notNull(),
    studentMessage: text("student_message"),
    aiResponse: text("ai_response"),
    timeSpentOnPageSeconds: integer("time_spent_on_page_seconds"),
    /** True = student confirmed understanding; false = needs re-explanation. */
    isUnderstood: boolean("is_understood"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    index("idx_page_interactions_session").on(t.sessionId),
    index("idx_page_interactions_student").on(t.studentId),
    index("idx_page_interactions_chunk").on(t.pdfChunkId),
  ],
);
